window.COURSE_DATA = [
  {
    "status": "Fulfilled",
    "course_code": "CSE111",
    "course_name": "Programming with Functions",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 2,
    "grade": "A",
    "term": "SP2021",
    "completion_date": "7/28/2021",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE210",
    "course_name": "Programming with Classes",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 2,
    "grade": "A",
    "term": "WI2022",
    "completion_date": "4/14/2022",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE212",
    "course_name": "Programming with Data Structures (SUB)Retaken",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 2,
    "grade": "A",
    "term": "26T2",
    "completion_date": "4/22/2026",
    "weight": 1.7
  },
  {
    "status": "Future",
    "course_code": "CSE270",
    "course_name": "Software Testing",
    "division": null,
    "credits_planned": 3,
    "credits_earned": 0,
    "grade": null,
    "term": null,
    "completion_date": null,
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE300",
    "course_name": "Professional Readiness",
    "division": "Upper Division",
    "credits_planned": 1,
    "credits_earned": 1,
    "grade": "A",
    "term": "26B3",
    "completion_date": "6/24/2026",
    "weight": 1.7
  },
  {
    "status": "Future",
    "course_code": "CSE310",
    "course_name": "Applied Programming",
    "division": null,
    "credits_planned": 3,
    "credits_earned": 0,
    "grade": null,
    "term": null,
    "completion_date": null,
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE325",
    "course_name": ".NET Software Development",
    "division": "Upper Division",
    "credits_planned": 3,
    "credits_earned": 3,
    "grade": "A",
    "term": "26B3",
    "completion_date": "6/24/2026",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE340",
    "course_name": "Web Backend Development",
    "division": "Upper Division",
    "credits_planned": 3,
    "credits_earned": 3,
    "grade": "B",
    "term": "FA2023",
    "completion_date": "12/20/2023",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "CSE341",
    "course_name": "Web Services",
    "division": "Upper Division",
    "credits_planned": 3,
    "credits_earned": 3,
    "grade": "A",
    "term": "WI24",
    "completion_date": "4/17/2024",
    "weight": 1.7
  },
  {
    "status": "Future",
    "course_code": "CSE370",
    "course_name": "Software Engineering Principles",
    "division": null,
    "credits_planned": 2,
    "credits_earned": 0,
    "grade": null,
    "term": null,
    "completion_date": null,
    "weight": 1.7
  },
  {
    "status": "Future",
    "course_code": "CSE499",
    "course_name": "Senior Project",
    "division": null,
    "credits_planned": 3,
    "credits_earned": 0,
    "grade": null,
    "term": null,
    "completion_date": null,
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "WDD130",
    "course_name": "Web Fundamentals",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 2,
    "grade": "A",
    "term": "SP2021",
    "completion_date": "7/28/2021",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "WDD131",
    "course_name": "Dynamic Web Fundamentals",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 2,
    "grade": "A-",
    "term": "26T1",
    "completion_date": "2/25/2026",
    "weight": 1.7
  },
  {
    "status": "Current",
    "course_code": "WDD231",
    "course_name": "Web Frontend Development I",
    "division": "Lower Division",
    "credits_planned": 2,
    "credits_earned": 0,
    "grade": null,
    "term": "26B4",
    "completion_date": null,
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "WDD330",
    "course_name": "Web Frontend Development II",
    "division": "Upper Division",
    "credits_planned": 3,
    "credits_earned": 3,
    "grade": "A",
    "term": "SP2023",
    "completion_date": "7/26/2023",
    "weight": 1.7
  },
  {
    "status": "Fulfilled",
    "course_code": "WDD430",
    "course_name": "Web Full-Stack Development",
    "division": "Upper Division",
    "credits_planned": 3,
    "credits_earned": 3,
    "grade": "A",
    "term": "26T1",
    "completion_date": "2/25/2026",
    "weight": 1.7
  }
];
